/* بوتيك عهود — كتالوج المنتجات (ر.س)
   صور محتشمة فقط: عبايات، حجابات، ملابس مغطاة
*/
const P = (id) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=900`;

const PRODUCTS = [
  {
    id: "oh-001",
    name: { en: "Ohood Evening Abaya", ar: "عباية عهود المسائية" },
    category: "abayas",
    price: 890,
    compareAt: 1100,
    badge: "new",
    colors: ["#1a1a1a", "#2c1810", "#4a3728"],
    sizes: ["S", "M", "L", "XL"],
    image: P(35324619),
    hoverImage: P(35324617),
    desc: {
      en: "Fluid crepe abaya with soft gold piping. Designed for Riyadh evenings — full coverage, refined drape.",
      ar: "عباية كريب انسيابية بخطوط ذهبية ناعمة. صُممت لأمسيات الرياض — تغطية كاملة وقصة راقية.",
    },
    tags: ["modest", "evening", "riyadh"],
  },
  {
    id: "oh-002",
    name: { en: "Desert Rose Modest Dress", ar: "فستان وردة الصحراء" },
    category: "dresses",
    price: 640,
    compareAt: null,
    badge: "bestseller",
    colors: ["#c4a4a0", "#8b5a5a", "#f5e6e0"],
    sizes: ["XS", "S", "M", "L"],
    image: P(35263628),
    hoverImage: P(35324626),
    desc: {
      en: "Long-sleeve modest dress in desert-rose tones. Covered shoulders, refined length.",
      ar: "فستان محتشم بأكمام طويلة بدرجات ورد الصحراء. أكتاف مغطاة وطول أنيق يناسب حرارة الرياض.",
    },
    tags: ["new-in", "day", "modest"],
  },
  {
    id: "oh-003",
    name: { en: "Wafa Modest Set", ar: "طقم وفاء" },
    category: "sets",
    price: 720,
    compareAt: 850,
    badge: "new",
    colors: ["#e8dfd0", "#d4c4a8", "#f7f3eb"],
    sizes: ["S", "M", "L", "XL"],
    image: P(35263626),
    hoverImage: P(35263627),
    desc: {
      en: "Two-piece modest set for Tahlia cafés and Diriyah weekends. Long sleeves, breathable fabric.",
      ar: "طقم محتشم من قطعتين لمقاهي التحلية وعطلات الدرعية. أكمام طويلة وقماش مريح.",
    },
    tags: ["casual", "summer", "modest"],
  },
  {
    id: "oh-004",
    name: { en: "Sama Jalabiya", ar: "جلابية سما" },
    category: "jalabiyas",
    price: 580,
    compareAt: null,
    badge: null,
    colors: ["#f8f4ef", "#e8d5c4", "#d4a574"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: P(35324621),
    hoverImage: P(35324630),
    desc: {
      en: "Airy jalabiya with delicate cuff embroidery. Full length, hostess-ready.",
      ar: "جلابية خفيفة بتطريز ناعم على الأكمام. طول كامل، مثالية لضيافة تجمعات الرياض.",
    },
    tags: ["modest", "home"],
  },
  {
    id: "oh-005",
    name: { en: "Black Structured Abaya", ar: "عباية سوداء بهيكل" },
    category: "outerwear",
    price: 980,
    compareAt: 1200,
    badge: "limited",
    colors: ["#0d0d0d", "#1c1c1c"],
    sizes: ["XS", "S", "M", "L"],
    image: P(35324631),
    hoverImage: P(35324619),
    desc: {
      en: "Structured black abaya for meetings and events. Strong silhouette, full coverage.",
      ar: "عباية سوداء بهيكل أنيق للاجتماعات والفعاليات. قصة قوية مع تغطية محتشمة كاملة.",
    },
    tags: ["work", "evening", "modest"],
  },
  {
    id: "oh-006",
    name: { en: "Gold Horizon Earrings", ar: "أقراط أفق الذهب" },
    category: "accessories",
    price: 280,
    compareAt: null,
    badge: "new",
    colors: ["#c9a84c"],
    sizes: ["One Size"],
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=80",
    hoverImage: "https://images.pexels.com/photos/1191531/pexels-photo-1191531.jpeg?auto=compress&cs=tinysrgb&w=800",
    desc: {
      en: "18k gold-plated geometric hoops. The finishing note for every Ohood look.",
      ar: "أقراط هندسية مطلية ذهب ١٨ قيراط. اللمسة الأخيرة لكل إطلالة من بوتيك عهود.",
    },
    tags: ["jewelry"],
  },
  {
    id: "oh-007",
    name: { en: "Riyadh Night Abaya", ar: "عباية ليل الرياض" },
    category: "dresses",
    price: 1450,
    compareAt: null,
    badge: "limited",
    colors: ["#1a0a14", "#0a0a0a", "#2a1a2a"],
    sizes: ["S", "M", "L"],
    image: P(35324617),
    hoverImage: P(35324626),
    desc: {
      en: "Floor-length evening abaya with subtle shimmer. Full coverage for celebrations.",
      ar: "عباية سهرة طويلة بلمعان خفيف. تغطية كاملة لليالي الحفلات والمناسبات الخاصة.",
    },
    tags: ["evening", "occasion", "modest"],
  },
  {
    id: "oh-008",
    name: { en: "Soft Wide Modest Pants", ar: "بنطلون واسع محتشم" },
    category: "sets",
    price: 420,
    compareAt: null,
    badge: null,
    colors: ["#2c2c2c", "#5c5346", "#f5f0e8"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: P(8148577),
    hoverImage: P(35263626),
    desc: {
      en: "High-rise wide modest trousers. Pair with a long tunic or abaya top.",
      ar: "بنطلون واسع بخصر عالٍ وقصة انسيابية. ينسجم مع تونيك طويل أو توب عباية.",
    },
    tags: ["work", "casual", "modest"],
  },
  {
    id: "oh-009",
    name: { en: "Pearl Abaya Coat", ar: "معطف عباية لؤلؤي" },
    category: "abayas",
    price: 1120,
    compareAt: 1350,
    badge: "bestseller",
    colors: ["#f2ebe3", "#e8e0d5", "#1a1a1a"],
    sizes: ["S", "M", "L", "XL"],
    image: P(35263627),
    hoverImage: P(35324621),
    desc: {
      en: "Coat-style abaya in pearl crepe. Architectural collar — modern Riyadh essential.",
      ar: "عباية بقصة معطف من كريب لؤلؤي. ياقة معمارية وأزرار مخفية — أساسي عصري للرياض.",
    },
    tags: ["modest", "work"],
  },
  {
    id: "oh-010",
    name: { en: "Silk Hijab — Palm Motif", ar: "حجاب حرير — نقشة النخيل" },
    category: "accessories",
    price: 320,
    compareAt: null,
    badge: null,
    colors: ["#8b4513", "#1a3a2a", "#c9a84c"],
    sizes: ["One Size"],
    image: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?w=800&q=80",
    desc: {
      en: "Pure silk hijab with a subtle palm motif. Soft drape for everyday modest styling.",
      ar: "حجاب حرير خالص بنقشة نخيل خفيفة. انسيابية ناعمة للتنسيق اليومي المحتشم.",
    },
    tags: ["accessories", "hijab"],
  },
  {
    id: "oh-011",
    name: { en: "Ivory Guest Abaya", ar: "عباية الضيافة العاجية" },
    category: "dresses",
    price: 780,
    compareAt: null,
    badge: "new",
    colors: ["#faf6f1", "#e8dcd0"],
    sizes: ["XS", "S", "M", "L"],
    image: P(35324626),
    hoverImage: P(35324630),
    desc: {
      en: "Modest ivory guest abaya. Covered shoulders and soft volume for weddings and iftars.",
      ar: "عباية ضيافة عاجية محتشمة بأكتاف مغطاة وحجم ناعم. مثالية للأفراح والإفطارات.",
    },
    tags: ["occasion", "modest"],
  },
  {
    id: "oh-012",
    name: { en: "Structured Mini Bag", ar: "حقيبة ميني بهيكل" },
    category: "accessories",
    price: 540,
    compareAt: 650,
    badge: "bestseller",
    colors: ["#1a1a1a", "#8b5a3c", "#f5f0e8"],
    sizes: ["One Size"],
    image: "https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=800",
    hoverImage: "https://images.pexels.com/photos/9428775/pexels-photo-9428775.jpeg?auto=compress&cs=tinysrgb&w=800",
    desc: {
      en: "Compact structured bag in Italian leather. City-ready for phone and essentials.",
      ar: "حقيبة مدمجة بهيكل من جلد إيطالي. تتسع للجوال والمحفظة — جاهزة للمدينة.",
    },
    tags: ["bags"],
  },
];

const CATEGORIES = [
  { id: "all", en: "All", ar: "الكل" },
  { id: "new", en: "New In", ar: "وصل حديثاً" },
  { id: "abayas", en: "Abayas", ar: "عبايات" },
  { id: "dresses", en: "Dresses", ar: "فساتين" },
  { id: "jalabiyas", en: "Jalabiyas", ar: "جلابيات" },
  { id: "sets", en: "Sets & Separates", ar: "أطقم وقطع" },
  { id: "outerwear", en: "Outerwear", ar: "ملابس خارجية" },
  { id: "accessories", en: "Accessories", ar: "إكسسوارات" },
];

const I18N = {
  ar: {
    dir: "rtl",
    brand: "عهود",
    brandFull: "بوتيك عهود",
    tagline: "أناقة تحتفظ بوعودها — للمرأة الرياضيّة العصرية",
    nav: {
      home: "الرئيسية",
      shop: "تسوقي",
      new: "وصل حديثاً",
      abayas: "عبايات",
      about: "قصتنا",
      contact: "تواصلي",
    },
    hero: {
      eyebrow: "الرياض · تأسس ٢٠٢٦",
      title: "وعود من الأناقة المحتشمة",
      sub: "عبايات وجلابيات وقصات مغطاة منتقاة بعناية لامرأة الرياض — راقية ومحافظة وصادقة في كل تفصيلة. توصيل في نفس اليوم داخل العاصمة.",
      cta: "تسوقي المجموعة",
      cta2: "اكتشفي العبايات",
    },
    trust: {
      delivery: "توصيل في نفس اليوم بالرياض",
      returns: "إرجاع مجاني خلال ١٤ يوماً",
      cod: "الدفع عند الاستلام",
      pay: "تابي وتمارا",
    },
    sections: {
      categories: "تسوقي حسب الإطلالة",
      featured: "مختارات هذا الأسبوع",
      riyadh: "صُممت لحياة الرياض",
      story: "لماذا عهود",
      reviews: "محبوبة في العاصمة",
      journal: "من الأتيليه",
      newsletter: "انضمي لعائلة عهود",
      newsletterSub: "إصدارات محتشمة جديدة وعروض خاصة ونصائح تنسيق — نرسلها بكل ود.",
      subscribe: "اشتركي",
      emailPlaceholder: "بريدك الإلكتروني",
      viewAll: "عرض الكل",
      addToBag: "أضيفي إلى الحقيبة",
      quickView: "عرض سريع",
      sar: "ر.س",
      size: "المقاس",
      color: "اللون",
      wishlist: "المفضلة",
      bag: "الحقيبة",
      emptyBag: "حقيبتك فارغة",
      emptyWish: "احفظي القطع التي تحبينها",
      checkout: "إتمام الطلب",
      continue: "متابعة التسوق",
      total: "الإجمالي",
      freeShip: "توصيل مجاني للطلبات فوق ٤٠٠ ر.س",
      filter: "تصفية",
      sort: "ترتيب",
      sortNew: "الأحدث",
      sortPriceAsc: "السعر: من الأقل",
      sortPriceDesc: "السعر: من الأعلى",
      results: "قطعة",
      soldOut: "نفدت الكمية",
      aboutTitle: "وُلدت في الرياض",
      aboutBody:
        "بوتيك عهود وعدٌ بالأناقة المحتشمة. نقدّم للمرأة التي تنتقل بين المجلس والمكتب والمساء قطعاً تحترم التغطية والقيم دون التخلي عن القصّة العصرية — مصمّمة لمناخ السعودية وثقتها. كل قطعة وعد بالجودة، وكل طلب وعد بالعناية.",
      riyadhPoints: [
        { t: "نفس اليوم في الرياض", d: "اطلبي قبل الساعة ٢ ظهراً للتوصيل في نفس اليوم." },
        { t: "جرّبي في المنزل", d: "إرجاع مجاني خلال ١٤ يوماً. المقاس يجب أن يكون مريحاً." },
        { t: "تنسيق عبر واتساب", d: "منسّقات عهود في الرياض يساعدنكِ على بناء إطلالة محتشمة." },
      ],
      footer: {
        shop: "تسوقي",
        help: "المساعدة",
        company: "الشركة",
        shipping: "الشحن والتوصيل",
        returns: "الإرجاع",
        sizeGuide: "دليل المقاسات",
        faq: "الأسئلة الشائعة",
        about: "عن بوتيك عهود",
        careers: "الوظائف",
        privacy: "الخصوصية",
        rights: "© ٢٠٢٦ بوتيك عهود. الرياض، المملكة العربية السعودية.",
        vat: "جاهز لضريبة القيمة المضافة · سجل تجاري",
      },
    },
  },
  en: {
    dir: "ltr",
    brand: "Ohood",
    brandFull: "Boutique Ohood",
    tagline: "Elegance that keeps its promises — for the modern Riyadh woman",
    nav: {
      home: "Home",
      shop: "Shop",
      new: "New In",
      abayas: "Abayas",
      about: "Our Story",
      contact: "Contact",
    },
    hero: {
      eyebrow: "Riyadh · Est. 2026",
      title: "Promises of modest elegance",
      sub: "Curated abayas, jalabiyas, and covered silhouettes for Riyadh women — refined, respectful, and true in every detail. Same-day delivery across the capital.",
      cta: "Shop collection",
      cta2: "Explore abayas",
    },
    trust: {
      delivery: "Same-day delivery in Riyadh",
      returns: "14-day free returns",
      cod: "Cash on delivery",
      pay: "Tabby & Tamara",
    },
    sections: {
      categories: "Shop by mood",
      featured: "Featured this week",
      riyadh: "Made for Riyadh life",
      story: "Why Ohood",
      reviews: "Loved in the capital",
      journal: "From the atelier",
      newsletter: "Join the Ohood circle",
      newsletterSub: "New modest drops, private sales, and Riyadh styling notes — with care.",
      subscribe: "Subscribe",
      emailPlaceholder: "Your email",
      viewAll: "View all",
      addToBag: "Add to bag",
      quickView: "Quick view",
      sar: "SAR",
      size: "Size",
      color: "Color",
      wishlist: "Wishlist",
      bag: "Bag",
      emptyBag: "Your bag is empty",
      emptyWish: "Save pieces you love",
      checkout: "Checkout",
      continue: "Continue shopping",
      total: "Total",
      freeShip: "Free delivery on orders over SAR 400",
      filter: "Filter",
      sort: "Sort",
      sortNew: "Newest",
      sortPriceAsc: "Price: Low to High",
      sortPriceDesc: "Price: High to Low",
      results: "pieces",
      soldOut: "Sold out",
      aboutTitle: "Born in Riyadh",
      aboutBody:
        "Boutique Ohood is a promise of modest elegance. We design and curate pieces that honor coverage and values without sacrificing modern silhouette — tailored for Saudi climate and confidence. Every piece is a promise of quality; every order a promise of care.",
      riyadhPoints: [
        { t: "Same-day Riyadh", d: "Order before 2 PM for capital delivery the same day." },
        { t: "Try at home", d: "14-day free returns. Fit should feel effortless." },
        { t: "WhatsApp styling", d: "Ohood stylists in Riyadh help you build modest looks." },
      ],
      footer: {
        shop: "Shop",
        help: "Help",
        company: "Company",
        shipping: "Shipping & delivery",
        returns: "Returns",
        sizeGuide: "Size guide",
        faq: "FAQ",
        about: "About Boutique Ohood",
        careers: "Careers",
        privacy: "Privacy",
        rights: "© 2026 Boutique Ohood. Riyadh, Kingdom of Saudi Arabia.",
        vat: "VAT ready · CR registered",
      },
    },
  },
};

const REVIEWS = [
  {
    name: { en: "Noura Al-Saud", ar: "نورة آل سعود" },
    city: { en: "Al Nakheel, Riyadh", ar: "النخيل، الرياض" },
    text: {
      en: "Finally a boutique that keeps its promise — modest Riyadh evenings, exceptional abayas.",
      ar: "أخيراً بوتيك يفي بوعده — أمسيات الرياض المحتشمة وعبايات بجودة استثنائية.",
    },
    stars: 5,
  },
  {
    name: { en: "Reem Al-Harbi", ar: "ريم الحربي" },
    city: { en: "Diplomatic Quarter", ar: "الحي الدبلوماسي" },
    text: {
      en: "Same-day delivery before my dinner. Ohood styling on WhatsApp was so thoughtful.",
      ar: "وصل في نفس اليوم قبل عشائي. تنسيق عهود عبر واتساب كان راقياً جداً.",
    },
    stars: 5,
  },
  {
    name: { en: "Lama Al-Qahtani", ar: "لمى القحطاني" },
    city: { en: "Al Olaya", ar: "العليا" },
    text: {
      en: "The Wafa set is my office uniform now. Modest, breathable, and polished.",
      ar: "طقم وفاء أصبح زيّي للعمل. محتشم ومريح وأنيق.",
    },
    stars: 5,
  },
];
